image: maven:3-jdk-11-slim

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - cd HAPark
    - mvn clean test surefire-report:report
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - HAPark/target/surefire-reports/TEST-*.xml
  when: always

build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - cd HAPark
    - mvn package
  artifacts:
    paths:
      - HAPark/target/*.jar
  when: always

deploy_stage:
  stage: deploy
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - cd HAPark
    - dpl --provider=heroku --app=$HEROKU_APP_STAGE --api-key=$HEROKU_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual

deploy_prod:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - cd HAPark
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual


deploy_release:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - cd HAPark
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      when: always